chore: PC-10133 Move AlertPolicy to separate package
nobl9/nobl9-go pull request #184
Opened 2023-11-29 08:55 UTC by daniel-zelazny

This PR:

- moves AlertPolicy to separate package and rewrites its validation to use validaiton library.
- removes PublicAlertMethod
- add temporary AlertMethodRef package allowing to return AlertMethod details with AlertPolicy in old manner.
- introduces fix to assert method allowing to look for error match for more than one error
- moves Severity and Measurement object definitions to alertpolicy package because they are used only with this particular context

2023-12-12 12:20 UTC, nieomylnieja requested changes

2023-12-13 11:34 UTC, nieomylnieja requested changes

2023-12-13 12:35 UTC, nieomylnieja requested changes

2023-12-14 11:43 UTC, nieomylnieja approved these changes

2023-12-14 11:44 UTC, nieomylnieja commented
nice job! This was I think the most tangled up object in here :)

2023-12-18 09:44 UTC, nieomylnieja requested changes

2023-12-18 10:11 UTC, nieomylnieja approved these changes

2023-12-18 10:13 UTC, merged

2026-05-14 04:43 UTC, navayla777-dotcom reviewed
Altert policy moving #49  dashboard platform